"""
Author: Eszter Bokanyi, e.bokanyi@uva.nl, 2024.11.12.

This script takes the all adjacency matrices saved as npz in a given folder
generated by network_generator.py, and combines
them into one single npz file edges.npz in the same folder, then deletes the original files.

Input:
------
 * all "*.npz" files in a folder
 * these should be binary encoded adjacency matrices of layers
 * ATTENTION: it deletes the files once finished!

Output:
-------
    * edges.npz, the sum of the above matrices, into the same folder

Usage:
------
    /c/mambaforge/envs/9629/python.exe 04_combine_layers.py "2023\\V3"
        * first argument: folder name that contains the files, and where output goes

    for year in `seq 2009 2022`
    do
        /c/mambaforge/envs/9629/python.exe 04_combine_layers.py $year"\\V3"
    done
"""

from scipy.sparse import load_npz, save_npz
import sys
import os

folder = sys.argv[1]
files = []

for f in os.listdir(folder):
    if f.endswith('npz'):
        files.append(f)

if len(f)==0:
    ValueError(f"No edge files (*.npz) found in folder {folder}!")
else:
    print("Edge files to be merged:")
    print("\n".join(files))
# creating adjacency matrix "basis" by reading in the very first file
# this determines matrix size
# and already loads data
f = files[0]

print(f"Loading initial {os.path.join(folder,f)}.")
A = load_npz(os.path.join(folder,f))
print("Number of nonzero elements:",A.nnz)

# stacking all other files on top
for f in files[1:]:
    print(f"Loading {os.path.join(folder,f)}.")
    temp = load_npz(os.path.join(folder,f))
    print("Number of nonzero elements in temp:",temp.nnz)
    print("Addition...")
    A+=temp
    print("Number of nonzero elements in A:",A.nnz)
    print("Done.")

output = os.path.join(folder,"edges.npz")
print(f"Saving to {output}...")
save_npz(output,A)
print("Done.")

print("Deleting old files...")
# for f in files:
    # os.remove(os.path.join(folder,f))
print("Done.")
    